services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    restart: unless-stopped
    expose:
        - "9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - monitoring
  
  loki:
    image: grafana/loki:3.2.1
    container_name: loki
    restart: unless-stopped
    expose:
      - 3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:11.2.2
    container_name: grafana
    restart: unless-stopped
    expose:
     - 3000
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    depends_on:
      - prometheus
      - loki
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    restart: unless-stopped
    expose:
      - "9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - monitoring

  proxy:
    image: nginx:stable-alpine3.23
    container_name: proxy
    restart: unless-stopped
    ports:
      - 80:8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - grafana
      - loki
    entrypoint:
      - /usr/sbin/nginx
      - -g
      - daemon off;
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,nosuid,noexec,size=64m,mode=1777
      - /var/cache/nginx:rw,nosuid,size=64m,mode=1777
      - /var/run:rw,nosuid,size=16m,mode=1777
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    networks:
      - monitoring

volumes:
  prometheus-data:
  loki-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge